### ISSUE TITLE
Source of CX properties (logP, logD)

### ISSUE THREAD

**Issue by ellimilial** [chembl/chembl_data_issues#11]
Dear ChEMBL team,

I wanted to double check the source of CX properties (i.e. CX_LogP, CX_MOST_BPKA etc.) in the latest (ChEMBL 33) release. 

1) [ChEMBL FAQ](https://chembl.gitbook.io/chembl-interface-documentation/frequently-asked-questions/drug-and-compound-questions#can-you-provide-some-details-on-how-chembl-compound-properties-e.g.-logp-mw-psa-..-are-calculated) states that since version 26, they are "calculated using ChemAxon tools".

2) The latest I could find in the publications was in [Mendez et al 2019](https://doi.org/10.1093/nar/gky1075), which concerned version 24 indicating they were "still calculated with ACD/Labs software (12.01)". I could not find any updates since.

3) [API schema](https://www.ebi.ac.uk/chembl/api/data/substructure/schema) notes ACD/Labs 12.01.

Your help would be much appreciated!

**Comment by Emma-Manners** [comment]
Thanks for the question. 

We have been using ChemAxon tools since version 26; the FAQs and release notes are correct (http://chembl.blogspot.com/2020/03/chembl-26-released.html). The properties calculated with ChemAxon tools have the CX_prefix.

We will update the API schema notes - thanks for highlighting this error.

**Comment by ellimilial** [comment]
Thank you very much for your response and for clarifying this for me!
