### ISSUE TITLE
retrieving drug mechanism using web services

### ISSUE THREAD

**Issue by inessmit** [chembl/chembl_data_issues#3]
Hello chemblites!

Could I ask why I don't get a mechanism for CHEMBL2 using the web services, while there is info on the interface?

web services:
https://www.ebi.ac.uk/chembl/api/data/mechanism?molecule_chembl_id=CHEMBL2
vs.
interface:
https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2

Doesn't seem to be related to the fact the target is a protein family, as for another random example with protein family as target I do get info:
https://www.ebi.ac.uk/chembl/api/data/mechanism?molecule_chembl_id=CHEMBL101

Thanks a lot and I'm sorry if I'm missing something!
Ines

**Comment by Emma-Manners** [comment]
The drug mechanism has been mapped to the approved salt PRAZOSIN HYDROCHLORIDE (CHEMBL1558) rather than the parent compound PRAZOSIN (CHEMBL2).

On the interface we map the mechanisms over to the parent compounds. However, when using the database/web services, compounds will need to be linked through the molecule_hierarchy in order to retrieve mechanisms across alternative compound forms. 

e.g. 
 
select *
from drug_mechanism
where molregno in
    (select molregno
    from molecule_hierarchy
    where (
        parent_molregno in
        (select distinct molregno from molecule_dictionary where chembl_id = 'CHEMBL2') 
        or molregno in
        (select distinct molregno from molecule_dictionary where chembl_id = 'CHEMBL2')
               )
     );
